// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SvitloSk.Publisher.Runtime.Persistence;

#nullable disable

namespace SvitloSk.Publisher.Runtime.Persistence.Migrations
{
    [DbContext(typeof(SvitloSkDbContext))]
    [Migration("20260810064617_P5_025_OutboxConcurrency")]
    partial class P5_025_OutboxConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SvitloSk.Publisher.Domain.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Editions");
                });

            modelBuilder.Entity("SvitloSk.Publisher.Domain.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Addresses")
                        .HasColumnType("jsonb");

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("HasTomorrowForecast")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PublicationPackageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScheduleHash")
                        .HasColumnType("text");

                    b.Property<string>("TerritoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PublicationPackageId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("SvitloSk.Publisher.Domain.PublicationPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EditionId");

                    b.ToTable("PublicationPackages");
                });

            modelBuilder.Entity("SvitloSk.Publisher.Runtime.Persistence.ExternalPublicationIdentity", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublicationId");

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("SvitloSk.Publisher.Runtime.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactType")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ClaimedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalIdentity")
                        .HasColumnType("text");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LeasedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OperationId");

                    b.HasIndex("Status", "NextRetryAt", "CreatedAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("SvitloSk.Publisher.Domain.Publication", b =>
                {
                    b.HasOne("SvitloSk.Publisher.Domain.PublicationPackage", null)
                        .WithMany("Publications")
                        .HasForeignKey("PublicationPackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SvitloSk.Publisher.Domain.PublicationPackage", b =>
                {
                    b.HasOne("SvitloSk.Publisher.Domain.Edition", null)
                        .WithMany("Packages")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SvitloSk.Publisher.Domain.Edition", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("SvitloSk.Publisher.Domain.PublicationPackage", b =>
                {
                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
