<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SvitloSk.Publisher.Application\SvitloSk.Publisher.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Svg.Skia" Version="2.0.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
